
// Generated by Together


import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Observable;
import java.util.Observer;

/**
 * An interface to SAAMS:
 * Gate Control Console:
 * Inputs events from gate staff, and displays aircraft and gate information.
 * This class is a controller for the GateInfoDatabase and the AircraftManagementDatabase: sends messages when aircraft dock, have finished disembarking, and are fully emarked and ready to depart.
 * This class also registers as an observer of the GateInfoDatabase and the
 * AircraftManagementDatabase, and is notified whenever any change occurs in those <<model>> elements.
 * See written documentation.
 *
 * @stereotype boundary/view/controller
 * @url element://model:project::SAAMS/design:view:::id1un8dcko4qme4cko4sw27
 * @url element://model:project::SAAMS/design:view:::id1jkohcko4qme4cko4svww
 * @url element://model:project::SAAMS/design:node:::id1un8dcko4qme4cko4sw27.node61
 */
public class GateConsole extends JFrame implements Observer, ActionListener {


    private final static String GATE = "Gate";
    private final JLabel gateStatusLabel = new JLabel("Gate Status");
    private final JLabel planeStatusLabel = new JLabel("Plane Status");
    private final JLabel flightCodeLabel = new JLabel("Flight Code");
    private final JLabel flightFromLabel = new JLabel("Flight From");
    private final JLabel flightToLabel = new JLabel("Flight To");
    private final JLabel nextStopLabel = new JLabel("Next Stop");
    private final JLabel noOfPassengersLabel = new JLabel("No. of Passengers");
    private final JLabel passengerNameLabel = new JLabel("Passenger Name");

    private final JTextField gateStatusTF = new JTextField("");
    private final JTextField planeStatusTF = new JTextField("");
    private final JTextField flightCodeTF = new JTextField("");
    private final JTextField flightFromTF = new JTextField("");
    private final JTextField flightToTF = new JTextField("");
    private final JTextField nextStopTF = new JTextField("");
    private final JTextField noOfPassengersTF = new JTextField("");
    private final JTextField passengerNameTF = new JTextField("");

    private final JButton planeDockedBtn = new JButton("Plane Docked");
    private final JButton planeUnloadedBtn = new JButton("Plane Unloaded");
    private final JButton flightReadyToDepartBtn = new JButton("Flight Ready To Depart");
    private final JButton addPassengerBtn = new JButton("Add Passenger");

    private DefaultListModel<String> passengerDefaultList = new DefaultListModel<>();
    private final JList passengerList = new JList(passengerDefaultList);

    /**
     * The GateConsole interface has access to the GateInfoDatabase.
     *
     * @supplierCardinality 1
     * @clientCardinality 0..*
     * @label accesses/observes
     * @directed
     */
    GateInfoDatabase gateInfoDatabase;

    /**
     * The GateConsole interface has access to the AircraftManagementDatabase.
     *
     * @supplierCardinality 1
     * @clientCardinality 0..*
     * @directed
     * @label accesses/observes
     */
    private AircraftManagementDatabase aircraftManagementDatabase;

    private ManagementRecord managementRecord;
    private int mCode;

    /**
     * This gate's gateNumber
     * - for identifying this gate's information in the GateInfoDatabase.
     */
    private int gateNumber;

    //TODO : CHANGE FROM FINDFROMFLIGHTCODE TO USE THE INDEX FOR THE PLAIN

    public GateConsole(AircraftManagementDatabase aircraftManagementDatabase, GateInfoDatabase gateInfoDatabase,
                       int gateNumber) {
        super(GATE);
        this.aircraftManagementDatabase = aircraftManagementDatabase;
        this.gateInfoDatabase = gateInfoDatabase;
        this.gateNumber = gateNumber;
        this.aircraftManagementDatabase.addObserver(this);
        this.gateInfoDatabase.addObserver(this);
        initiateGUI();
        createLabels();
        createButtons();
        createTextFields();
        setVisible(true);
    }

    public void createLabels() {
        gateStatusLabel.setBounds(180, 20, 150, 20);
        add(gateStatusLabel);
        planeStatusLabel.setBounds(180, 50, 100, 20);
        add(planeStatusLabel);
        flightCodeLabel.setBounds(180, 80, 100, 20);
        add(flightCodeLabel);
        flightFromLabel.setBounds(180, 110, 100, 20);
        add(flightFromLabel);
        flightToLabel.setBounds(180, 140, 100, 20);
        add(flightToLabel);
        nextStopLabel.setBounds(180, 170, 150, 20);
        add(nextStopLabel);
        noOfPassengersLabel.setBounds(180, 200, 150, 20);
        add(noOfPassengersLabel);
        passengerNameLabel.setBounds(180, 230, 150, 20);
        add(passengerNameLabel);

    }

    public void createButtons() {
        planeDockedBtn.addActionListener(this);
        planeDockedBtn.setBounds(220, 260, 200, 30);
        add(planeDockedBtn);
        planeUnloadedBtn.addActionListener(this);
        planeUnloadedBtn.setBounds(220, 290, 200, 30);
        add(planeUnloadedBtn);
        flightReadyToDepartBtn.addActionListener(this);
        flightReadyToDepartBtn.setBounds(220, 320, 200, 30);
        add(flightReadyToDepartBtn);
        addPassengerBtn.addActionListener(this);
        addPassengerBtn.setBounds(220, 350, 200, 30);
        add(addPassengerBtn);
    }

    public void createTextFields() {
        passengerList.setVisible(true);
        passengerList.setBounds(5, 20, 160, 180);
        add(passengerList);
        gateStatusTF.setEditable(false);
        gateStatusTF.setBounds(300, 20, 180, 25);
        add(gateStatusTF);
        planeStatusTF.setEditable(false);
        planeStatusTF.setBounds(300, 50, 180, 25);
        add(planeStatusTF);
        flightCodeTF.setEditable(false);
        flightCodeTF.setBounds(300, 80, 180, 25);
        add(flightCodeTF);
        flightFromTF.setEditable(false);
        flightFromTF.setBounds(300, 110, 180, 25);
        add(flightFromTF);
        flightToTF.setEditable(false);
        flightToTF.setBounds(300, 140, 180, 25);
        add(flightToTF);
        nextStopTF.setEditable(false);
        nextStopTF.setBounds(300, 170, 180, 25);
        add(nextStopTF);
        noOfPassengersTF.setEditable(false);
        noOfPassengersTF.setBounds(300, 200, 180, 25);
        add(noOfPassengersTF);
        passengerNameTF.setEditable(true);
        passengerNameTF.setBounds(300, 230, 180, 25);
        add(passengerNameTF);
    }

    public void initiateGUI() {
        setLayout(null);
        setTitle(GATE + gateNumber);
        setBackground(Color.CYAN);
        setLocation(40, 40);
        setSize(550, 500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    public ManagementRecord plainIndexFromFlightCode() {
        if ((flightCodeTF.getText()) != null) {
            return aircraftManagementDatabase.findMrFromFlightCode(flightCodeTF.getText());
        }
        return null;
    }

    public void planeIndexForGate() {
        for (int i = 0; i < aircraftManagementDatabase.maxMRs; i++) {
            if (aircraftManagementDatabase.getStatus(i) == ManagementRecord.TAXIING
                    && aircraftManagementDatabase.getGate(i) == this.gateNumber) {
                mCode = i;
                displayInfoOnGate();
            }
        }
    }

    public void displayInfoOnGate() {
        removeInfoOnGate();
        gateStatusTF.setText(gateInfoDatabase.statusToText(gateInfoDatabase.getStatus(gateNumber - 1)));
        //TODO CREATE METHOD IN AMD statusToString
        planeStatusTF.setText(aircraftManagementDatabase.getStatus(mCode) + "");
        flightCodeTF.setText(aircraftManagementDatabase.getFlightCode(mCode));
        flightFromTF.setText(aircraftManagementDatabase.getItinerary(mCode).getFrom());
        flightToTF.setText(aircraftManagementDatabase.getItinerary(mCode).getTo());
        nextStopTF.setText(aircraftManagementDatabase.getItinerary(mCode).getNext());
        noOfPassengersTF.setText(aircraftManagementDatabase.getPassengerList(mCode).getListLength() + "");
    }

    public void removeInfoOnGate() {
        gateStatusTF.setText("");
        planeStatusTF.setText("");
        flightCodeTF.setText("");
        flightFromTF.setText("");
        flightToTF.setText("");
        nextStopTF.setText("");
    }

    @Override
    public void update(Observable o, Object arg) {
        planeIndexForGate();
//        plainIndexFromFlightCode();
    }

    private void displayPassengers() {
        managementRecord = plainIndexFromFlightCode();
        passengerDefaultList.removeAllElements();
        for (int i = 0; i < managementRecord.getPassengerList().getListLength(); i++) {
            passengerDefaultList.addElement(managementRecord.getPassengerList().getElement(i).getName());
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == planeDockedBtn) {
            gateInfoDatabase.docked(gateNumber - 1);
            aircraftManagementDatabase.setStatus(mCode, ManagementRecord.UNLOADING);
            displayInfoOnGate();
        }

        if (e.getSource() == planeUnloadedBtn) {
            aircraftManagementDatabase.setStatus(mCode, ManagementRecord.READY_CLEAN_AND_MAINT);
            displayInfoOnGate();
        }

        if (e.getSource() == addPassengerBtn) {
            if (plainIndexFromFlightCode() != null) {
                plainIndexFromFlightCode().addPassenger(new PassengerDetails(passengerNameTF.getText()));
                displayPassengers();
            }
        }
    }
}
