
// Generated by Together


import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.Observable;
import java.util.Observer;

/**
 * An interface to SAAMS:
 * Local Air Traffic Controller Screen:
 * Inputs events from LATC (a person), and displays aircraft information.
 * This class is a controller for the AircraftManagementDatabase: sending it messages to change the aircraft status information.
 * This class also registers as an observer of the AircraftManagementDatabase, and is notified whenever any change occurs in that <<model>> element.
 * See written documentation.
 * @stereotype boundary/view/controller
 * @url element://model:project::SAAMS/design:view:::id15rnfcko4qme4cko4swib
 * @url element://model:project::SAAMS/design:view:::id2fh3ncko4qme4cko4swe5
 * @url element://model:project::SAAMS/design:node:::id15rnfcko4qme4cko4swib.node107
 * @url element://model:project::SAAMS/design:view:::idwwyucko4qme4cko4sgxi
 */
public class LATC extends JFrame implements Observer, ActionListener {

  private final static String LATC_NAME = "Local Air Traffic Controls";
  private final JLabel controls = new JLabel("Controls");
  private final JLabel inbounds = new JLabel("Inbound");
  private final JButton allowApproachClearance = new JButton("Allow Approach Clearance");
  private final JButton confirmPlaneLanding = new JButton("Confirm Plane Has Landed");
  private final JLabel outBound = new JLabel("Outbound");
  private final JButton allocateDepartureSlot = new JButton("Allocate Departure Slot");
  private final JButton permitTakeOff = new JButton("Permit Takeoff");
  private final JLabel planeDetails = new JLabel("Plane Details");
  private DefaultListModel<String> selectedPlane = new DefaultListModel<>();
  private final JList planeDetailsTF = new JList(selectedPlane);
  private final JLabel planesJL = new JLabel("Planes");
  private DefaultListModel<String> planesIncoming = new DefaultListModel<>();
  private final JList planesTF = new JList(planesIncoming);


/**
  *  The Local Air Traffic Controller Screen interface has access to the AircraftManagementDatabase.
  * @supplierCardinality 1
  * @clientCardinality 1
  * @label accesses/observes
  * @directed*/

private AircraftManagementDatabase aircraftManagementDatabase;


  public LATC(AircraftManagementDatabase aircraftManagementDatabase) {
    super(LATC_NAME);
    this.aircraftManagementDatabase = aircraftManagementDatabase;
    //creating the buttons, labels and the text fields for this view
    initiateGUI();
    createLabels();
    createButtons();
    createTextFields();
    //adding functionality
    this.aircraftManagementDatabase.addObserver(this); //adds this view/controller as an observer to the changes made in the AircraftManagementDatabase
    setVisible(true);
}

  public void createLabels() {
    planesJL.setBounds(5, 20, 150, 20);
    add(planesJL);
    controls.setBounds(230, 40, 100, 20);
    add(controls);
    inbounds.setBounds(230, 65, 100, 20);
    add(inbounds);
    outBound.setBounds(230, 175, 100, 20);
    add(outBound);
    planeDetails.setBounds(230, 285, 100, 20);
    add(planeDetails);
  }

  public void createButtons() {
    allowApproachClearance.setBounds(170, 90, 200, 30);
    add(allowApproachClearance);
    confirmPlaneLanding.setBounds(170, 125, 200, 30);
    add(confirmPlaneLanding);
    permitTakeOff.setBounds(170, 200, 200, 30);
    add(permitTakeOff);
    permitTakeOff.addActionListener(this);
    allocateDepartureSlot.setBounds(170, 245, 200, 30);
    add(allocateDepartureSlot);
  }

  public void createTextFields() {
    planesTF.setVisible(true);
    planesTF.setBounds(5, 45, 160, 410);
    add(planesTF);
    planeDetailsTF.setBounds(170, 310, 200, 150);
    add(planeDetailsTF);
  }


  public void initiateGUI() {
    setLayout(null);
    setTitle(LATC_NAME);
    setBackground(Color.CYAN);
    setLocation(40, 40);
    setSize(400, 500);
    setDefaultCloseOperation(EXIT_ON_CLOSE);
  }


//  public String flightsLandingOrTransit() {
//    return aircraftManagementDatabase.getStatus()
//  }
  @Override
  public void actionPerformed(ActionEvent e) {

  }

  @Override
  public void update(Observable o, Object arg) {

  }
}
