package dev;// Generated by Together


/**
 * The details of an individual passenger: just a name for simplicity!
 * A dev.PassengerList holds a collection of dev.PassengerDetails.
 * @note One pasenger's personal details
 * @stereotype entity
 * @url element://model:project::SAAMS/design:view:::id1un8dcko4qme4cko4sw27
 * @url element://model:project::SAAMS/design:view:::id15rnfcko4qme4cko4swib
 * @url element://model:project::SAAMS/design:view:::id1jkohcko4qme4cko4svww
 */
public class PassengerDetails {

  private String passengerName;
  /**
   * Constructor: Just a name required.
   */
  public PassengerDetails(String name){
    this.passengerName = name;
  }

  /**
   * Return the name of this passenger.
   */
  public String getName(){
    return passengerName;
  }

  public String toString() {
    return passengerName;
  }
}
